version: '3'

services:
  streaming-server:
    build: ./streaming-server
    ports:
      - "1935:1935"
      - "8000:8000"
      - "8443:8443"
    volumes:
      - ./streaming-server:/app

  web-server:
    build: ./web-server
    ports:
      - "3000:3000"
    volumes:
      - ./web-server:/app
    depends_on:
      - redis
      - mongo

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
      
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"